# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'   # GitHub 只能用 glob 捕获 tag

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate tag format
        run: |
          echo "Tag: $GITHUB_REF_NAME"
          if [[ ! "$GITHUB_REF_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-dev\.[0-9]+)?$ ]]; then
            echo "❌ Tag format does not match pub.dev pattern!"
            echo "Expected: v<MAJOR>.<MINOR>.<PATCH> or v<MAJOR>.<MINOR>.<PATCH>-dev.<N>"
            exit 1
          fi
          echo "✅ Tag format is valid."

      - name: Publish to pub.dev
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          working-directory: ./   # 你的 package 路径，如果是单包仓库可用 ./
